version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "wplab_events"
    environment:
      - POSTGRES_USER=wplab
      - POSTGRES_PASSWORD=wplab123
      - POSTGRES_DB=events

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data